version: 2
jobs:
  build_cli:
    working_directory: ~/pxblue-cli
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Unit Tests
          command: |
            yarn test
      - run:
          name: Build
          command: |
            yarn build
      # Save the dist folder for use in future jobs.
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - bin

  build_angular:
      working_directory: ~/pxblue-cli
      docker:
          - image: circleci/node:12.16.3-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Build Angular Project
            command: |
              bin/pxb new angular --name=angulartest --lint --prettier

  build_react:
    working_directory: ~/pxblue-cli
    docker:
        - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build React Project
          command: |
            bin/pxb new react --name=reacttest --lint --prettier --language=typescript --template=blank


  build_react_native:
    working_directory: ~/pxblue-cli
    docker:
        - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build React Native Project
          # TODO: Using Expo for the test now because react-native link has stopped working on CircleCI
          command: |
            bin/pxb new react-native --name=reactnativetest --cli=expo --lint --prettier --language=typescript
            
  build_ionic:
    working_directory: ~/pxblue-cli
    docker:
        - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Ionic Project
          command: |
            bin/pxb new ionic --name=ionictest --lint --prettier
  publish:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish @pxblue/cli
          command:  |
            MASTER_VERSION=`node -p "require('./package.json').version"`
            NPM_LATEST_VERSION=`npm show @pxblue/cli version`
            if ! [ $MASTER_VERSION == $NPM_LATEST_VERSION ];
            then
                npm publish
            else
                echo "Latest version is already published."
            fi
workflows:
  version: 2
  pxblue_cli:
    jobs:
      - build_cli
      - build_angular:
          requires:
            - build_cli
          filters:
            branches:
              only:
                - master
                - dev
      - build_react:
          requires:
            - build_cli
          filters:
            branches:
              only:
                - master
                - dev
      - build_react_native:
          requires:
            - build_cli
          filters:
            branches:
              only:
                - master
                - dev
      - build_ionic:
          requires:
            - build_cli
          filters:
            branches:
              only:
                - master
                - dev
      - publish:
          requires:
            - build_angular
            - build_ionic
            - build_react
            - build_react_native
          filters:
            branches:
              only:
                - master
