version: 2
jobs:
  build:
    working_directory: ~/pxblue-cli
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Unit Tests
          command: |
            yarn test
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Create Projects
          command: |
            bin/pxb new angular --name=angulartest --lint
            bin/pxb new react --name=reacttest --lint --language=typescript
            bin/pxb new react-native --name=reactnativetest --cli=rnc --lint --language=typescript
            bin/pxb new ionic --name=ionictest --lint
