version: 2
jobs:
  build_cli:
    working_directory: ~/pxblue-cli
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Unit Tests
          command: |
            yarn test
      - run:
          name: Build
          command: |
            yarn build
      # Save the dist folder for use in future jobs.
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - bin

  build_angular:
      working_directory: ~/pxblue-cli
      docker:
          - image: circleci/node:12.6
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Build Angular Project
            command: |
              bin/pxb new angular --name=angulartest --lint


      # - run:
      #     name: Create Projects
      #     command: |
            
      #       bin/pxb new react --name=reacttest --lint --language=typescript
      #       bin/pxb new react-native --name=reactnativetest --cli=rnc --lint --language=typescript
      #       bin/pxb new ionic --name=ionictest --lint

workflows:
  version: 2
  pxblue_cli:
    jobs:
      - build_cli
      - build_angular:
          requires:
            - build_cli
          # filters:
          #   branches:
          #     only:
          #       - master
          #       - dev
      # - build_react:
      #     requires:
      #       - build_cli
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - dev
      # - build_react_native:
      #     requires:
      #       - build_cli
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - dev
      # - build_ionic:
      #     requires:
      #       - build_cli
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - dev